// Copyright © 2020-2021 The EVEN Solutions Developers Team

package bytes

import (
	"crypto/rand"
)

// RandBytes returns random generated bytes with given size.
func RandBytes(size int) []byte {
	b := make([]byte, size)
	_, _ = rand.Read(b)

	return b
}
